version: "3.8"
services:
  frontend:
    build:
      context: ./
    ports:
      - "3000:3000"
    container_name: "compose-container"
    stdin_open: true
    volumes:
      - ./src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  appvol:
    external: true
